on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.12"]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v7
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -e .[dev]
    - name: Lint with ruff
      run: ruff check .
    - name: Run tests
      run: pytest -q
