services:
  download:
    build: .
    image: rss-audio-downloader
    volumes:
      - "./config/:/app/config"
      - "./volume/work/:/app/mount/work"
    environment:
      CONFIG_PATH: /app/config/config.yaml
