apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-archive-backup.name" . }}
  labels:
    {{- include "git-archive-backup.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
